# Generated by Django 4.2.6 on 2023-10-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True)),
                ('initial_deposit', models.IntegerField()),
                ('profit', models.IntegerField()),
                ('loss', models.IntegerField()),
                ('net_equity', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
